export REDIS_PORT="6379"
export REDIS_HOST="redis-cluster-proxy.user-system-vaughnmedellins394"
export REDIS_PASSWORD="EJtetarG2IAqYX8P"
export LPNODE_URI="https://48fcf1da.vaughnmedellins394.myterminus.com/lpnode"
export RELAY_URI="https://5b4522f4.saidevgp01.relay-1-testnet.otmoic.cloud/relay"